params:
  epochs: 5
  batch_size: 32
  no_classes: 10
  input_shape: [28,28]
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  Validation_datasize: 5000
  patience: 5
  restore_best_weights: True

artifacts:
  artifacts_dir: artifacts 
  model_dir: model
  model_name: model_ann.h5
  plots_dir: plots
  
  plot_name: ann_graph
  Checkpoint_dir: checkpoints
  

logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs
